import { UpgradeType } from "../components/Dashboard/components/Upgrade";
export const upgradesRaw: UpgradeType[] = [
  {
    id: 0,
    image: "iron.png",
    title: "Iron Mine",
    profit: 1,
    quantity: 0,
    canPurchasable: false,
    sacrifice: 0,
  },
  {
    id: 1,
    image: "gold.png",
    title: "Gold Mine",
    profit: 100,
    quantity: 0,
    canPurchasable: false,
    sacrifice: 0,
  },
  {
    id: 2,
    image: "emerald.png",
    title: "Emerald Mine",
    profit: 10000,
    quantity: 0,
    canPurchasable: false,
    sacrifice: 0,
  },
  {
    id: 3,
    image: "ruby.png",
    title: "Ruby Mine",
    profit: 1000000,
    quantity: 0,
    canPurchasable: false,
    sacrifice: 0,
  },
  {
    id: 4,
    image: "sapphire.png",
    title: "Sapphire Mine",
    profit: 100000000,
    quantity: 0,
    canPurchasable: false,
    sacrifice: 0,
  },
  {
    id: 5,
    image: "worldstone.png",
    title: "World Mining",
    profit: 10000000000,
    quantity: 0,
    canPurchasable: false,
    sacrifice: 0,
  },
];
